CFLAGS = -g

all: test
.PHONY: all

.PHONY: test

.PHONY: clean

.PHONY: fclean
fclean: clean

.PHONY: re
re:
	$(MAKE) fclean
	$(MAKE) all

.PHONY: test_get_next_line_string_util_strlen
test: test_get_next_line_string_util_strlen
clean: clean_test_get_next_line_string_util_strlen
.PHONY: clean_test_get_next_line_string_util_strlen
clean_test_get_next_line_string_util_strlen:
	rm -f test_get_next_line_string_util_strlen.exe
test_get_next_line_string_util_strlen: test_get_next_line_string_util_strlen.exe
	./$<
test_get_next_line_string_util_strlen.exe: get_next_line_string_util_strlen.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_util_nl_pos
test: test_get_next_line_string_util_nl_pos
clean: clean_test_get_next_line_string_util_nl_pos
.PHONY: clean_test_get_next_line_string_util_nl_pos
clean_test_get_next_line_string_util_nl_pos:
	rm -f test_get_next_line_string_util_nl_pos.exe
test_get_next_line_string_util_nl_pos: test_get_next_line_string_util_nl_pos.exe
	./$<
test_get_next_line_string_util_nl_pos.exe: get_next_line_string_util_nl_pos.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_util_ln_len
test: test_get_next_line_string_util_ln_len
clean: clean_test_get_next_line_string_util_ln_len
.PHONY: clean_test_get_next_line_string_util_ln_len
clean_test_get_next_line_string_util_ln_len:
	rm -f test_get_next_line_string_util_ln_len.exe
test_get_next_line_string_util_ln_len: test_get_next_line_string_util_ln_len.exe
	./$<
test_get_next_line_string_util_ln_len.exe: get_next_line_string_util_ln_len.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_util_copy_0
test: test_get_next_line_string_util_copy_0
clean: clean_test_get_next_line_string_util_copy_0
.PHONY: clean_test_get_next_line_string_util_copy_0
clean_test_get_next_line_string_util_copy_0:
	rm -f test_get_next_line_string_util_copy_0.exe
test_get_next_line_string_util_copy_0: test_get_next_line_string_util_copy_0.exe
	./$<
test_get_next_line_string_util_copy_0.exe: get_next_line_string_util_copy_0.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_util_copy_nl
test: test_get_next_line_string_util_copy_nl
clean: clean_test_get_next_line_string_util_copy_nl
.PHONY: clean_test_get_next_line_string_util_copy_nl
clean_test_get_next_line_string_util_copy_nl:
	rm -f test_get_next_line_string_util_copy_nl.exe
test_get_next_line_string_util_copy_nl: test_get_next_line_string_util_copy_nl.exe
	./$<
test_get_next_line_string_util_copy_nl.exe: get_next_line_string_util_copy_nl.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_alloc_util_concat
test: test_get_next_line_string_alloc_util_concat
clean: clean_test_get_next_line_string_alloc_util_concat
.PHONY: clean_test_get_next_line_string_alloc_util_concat
clean_test_get_next_line_string_alloc_util_concat:
	rm -f test_get_next_line_string_alloc_util_concat.exe
test_get_next_line_string_alloc_util_concat: test_get_next_line_string_alloc_util_concat.exe
	./$<
test_get_next_line_string_alloc_util_concat.exe: get_next_line_string_alloc_util_concat.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_alloc_util_before_newline
test: test_get_next_line_string_alloc_util_before_newline
clean: clean_test_get_next_line_string_alloc_util_before_newline
.PHONY: clean_test_get_next_line_string_alloc_util_before_newline
clean_test_get_next_line_string_alloc_util_before_newline:
	rm -f test_get_next_line_string_alloc_util_before_newline.exe
test_get_next_line_string_alloc_util_before_newline: test_get_next_line_string_alloc_util_before_newline.exe
	./$<
test_get_next_line_string_alloc_util_before_newline.exe: get_next_line_string_alloc_util_before_newline.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_alloc_util_after_newline
test: test_get_next_line_string_alloc_util_after_newline
clean: clean_test_get_next_line_string_alloc_util_after_newline
.PHONY: clean_test_get_next_line_string_alloc_util_after_newline
clean_test_get_next_line_string_alloc_util_after_newline:
	rm -f test_get_next_line_string_alloc_util_after_newline.exe
test_get_next_line_string_alloc_util_after_newline: test_get_next_line_string_alloc_util_after_newline.exe
	./$<
test_get_next_line_string_alloc_util_after_newline.exe: get_next_line_string_alloc_util_after_newline.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^

.PHONY: test_get_next_line_string_alloc_util_strdup
test: test_get_next_line_string_alloc_util_strdup
clean: clean_test_get_next_line_string_alloc_util_strdup
.PHONY: clean_test_get_next_line_string_alloc_util_strdup
clean_test_get_next_line_string_alloc_util_strdup:
	rm -f test_get_next_line_string_alloc_util_strdup.exe
test_get_next_line_string_alloc_util_strdup: test_get_next_line_string_alloc_util_strdup.exe
	./$<
test_get_next_line_string_alloc_util_strdup.exe: get_next_line_string_alloc_util_strdup.c ../src/get_next_line.c ../src/get_next_line_utils.c
	$(CC) $(LDFLAGS) -o $@ $^
